org: simpleapp
app: lego
service: grocery-store-lambda

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "*"

functions:
  getStatus:
    handler: handler.getStatus
    events:
      - http:
          path: status
          method: get
          cors: true

  getProducts:
    handler: handler.getProducts
    events:
      - http:
          path: products
          method: get
          cors: true

  
  getCart:
    handler: handler.getCart
    events:
      - http:
          path: carts/{cartId}
          method: get
          cors: true

  createUser:
    handler: handler.createUser
    events:
      - http:
          path: api/users
          method: post
          cors: true
    timeout: 10 # Correct placement
    memorySize: 128 # Correct placement

  createPost: # Fixed indentation for createPost function
    handler: handler.createPost
    events:
      - http:
          path: post
          method: post
          cors: true

package:
  include:
    - node_modules/**
    - handler.js
    - package.json
