service: grocery-store-lambda

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "*"

functions:
  getStatus:
    handler: handler.getStatus
    events:
      - http:
          path: status
          method: get
          cors: true


  getProducts:
    handler: handler.getProducts
    events:
      - http:
          path: products
          method: get
          cors: true

package:
  include:
    - node_modules/**
